// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs eml-viewer`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "winmail-viewer",
    "icon": "📎",
    "name": {
      "en": "Winmail Viewer",
      "ja": "Winmail ビューア",
      "zh": "Winmail 查看器",
      "de": "Winmail Viewer",
      "es": "Winmail Viewer"
    },
    "desc": {
      "en": "Open a winmail.dat and download the real attachments.",
      "ja": "winmail.dat を開いて中の添付ファイルを取り出す。",
      "zh": "打开 winmail.dat，取出里面真正的附件。",
      "de": "winmail.dat öffnen und die echten Anhänge herunterladen.",
      "es": "Abre un winmail.dat y descarga los adjuntos reales."
    }
  },
  {
    "slug": "markdown-viewer",
    "icon": "📄",
    "name": {
      "en": "Markdown Viewer",
      "ja": "Markdownビューアー",
      "zh": "Markdown 查看器",
      "de": "Markdown-Betrachter",
      "es": "Visor de Markdown"
    },
    "desc": {
      "en": "Open a local .md file and read it as sanitized, rendered HTML.",
      "ja": "ローカルの.mdファイルを、サニタイズ済みのHTMLとして表示。",
      "zh": "打开本地 .md 文件，以净化后的 HTML 渲染显示。",
      "de": "Öffne eine lokale .md-Datei und lies sie als bereinigtes, gerendertes HTML.",
      "es": "Abre un archivo .md local y léelo como HTML renderizado y depurado."
    }
  },
  {
    "slug": "hex-viewer",
    "icon": "🔍",
    "name": {
      "en": "Hex Viewer",
      "ja": "Hex Viewer",
      "zh": "Hex Viewer",
      "de": "Hex Viewer",
      "es": "Hex Viewer"
    },
    "desc": {
      "en": "Inspect any file as a hex dump, right in your browser.",
      "ja": "どんなファイルもブラウザで 16 進ダンプとして表示。",
      "zh": "在浏览器中把任意文件显示为十六进制内容。",
      "de": "Beliebige Dateien im Browser als Hex-Dump ansehen.",
      "es": "Ver cualquier archivo como volcado hexadecimal en tu navegador."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'eml-viewer';
